$ErrorActionPreference = "Stop"

Set-Location "$PSScriptRoot\.."

$env:ATTENDANCE_REMINDER_ENABLED = "true"
$env:ATTENDANCE_REMINDER_ENTRY_URL = "https://your-domain.example.com/mobile/attendance"
$env:ATTENDANCE_REMINDER_CHECKIN_TEMPLATE_ID = "REPLACE_WITH_CHECKIN_TEMPLATE_ID"
$env:ATTENDANCE_REMINDER_CHECKOUT_TEMPLATE_ID = "REPLACE_WITH_CHECKOUT_TEMPLATE_ID"

Write-Host "ATTENDANCE_REMINDER_ENABLED=$env:ATTENDANCE_REMINDER_ENABLED"
Write-Host "ATTENDANCE_REMINDER_ENTRY_URL=$env:ATTENDANCE_REMINDER_ENTRY_URL"
Write-Host "ATTENDANCE_REMINDER_CHECKIN_TEMPLATE_ID=$env:ATTENDANCE_REMINDER_CHECKIN_TEMPLATE_ID"
Write-Host "ATTENDANCE_REMINDER_CHECKOUT_TEMPLATE_ID=$env:ATTENDANCE_REMINDER_CHECKOUT_TEMPLATE_ID"

mvn "-Dspring-boot.run.profiles=wsl" spring-boot:run
