export const ATTENDANCE_CHECK_IN_STATUS = {
  LOCATION_READY: 'LOCATION_READY',
  LOCATION_NOT_BOUND: 'LOCATION_NOT_BOUND',
  LOCATION_NOT_CONFIGURED: 'LOCATION_NOT_CONFIGURED',
  LOCATION_DISABLED: 'LOCATION_DISABLED',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  OUT_OF_RANGE: 'OUT_OF_RANGE',
  ALREADY_FINISHED: 'ALREADY_FINISHED',
  CHECK_IN_SUCCESS: 'CHECK_IN_SUCCESS',
  CHECK_OUT_SUCCESS: 'CHECK_OUT_SUCCESS'
}

export const ATTENDANCE_STATUS_OPTIONS = [
  { label: '全部', value: '' },
  { label: '上班打卡成功', value: ATTENDANCE_CHECK_IN_STATUS.CHECK_IN_SUCCESS },
  { label: '下班打卡成功', value: ATTENDANCE_CHECK_IN_STATUS.CHECK_OUT_SUCCESS },
  { label: '未配置打卡点', value: ATTENDANCE_CHECK_IN_STATUS.LOCATION_NOT_CONFIGURED },
  { label: '打卡点未启用', value: ATTENDANCE_CHECK_IN_STATUS.LOCATION_DISABLED },
  { label: '缺少定位', value: ATTENDANCE_CHECK_IN_STATUS.LOCATION_REQUIRED },
  { label: '超出范围', value: ATTENDANCE_CHECK_IN_STATUS.OUT_OF_RANGE },
  { label: '今日已完成', value: ATTENDANCE_CHECK_IN_STATUS.ALREADY_FINISHED }
]

export function getAttendanceStatusLabel(status) {
  return {
    [ATTENDANCE_CHECK_IN_STATUS.CHECK_IN_SUCCESS]: '上班打卡成功',
    [ATTENDANCE_CHECK_IN_STATUS.CHECK_OUT_SUCCESS]: '下班打卡成功',
    [ATTENDANCE_CHECK_IN_STATUS.LOCATION_NOT_CONFIGURED]: '未配置打卡点',
    [ATTENDANCE_CHECK_IN_STATUS.LOCATION_DISABLED]: '打卡点未启用',
    [ATTENDANCE_CHECK_IN_STATUS.LOCATION_REQUIRED]: '缺少定位',
    [ATTENDANCE_CHECK_IN_STATUS.OUT_OF_RANGE]: '超出范围',
    [ATTENDANCE_CHECK_IN_STATUS.ALREADY_FINISHED]: '今日已完成',
    [ATTENDANCE_CHECK_IN_STATUS.LOCATION_NOT_BOUND]: '未绑定单位',
    [ATTENDANCE_CHECK_IN_STATUS.LOCATION_READY]: '可打卡'
  }[status] || status || '-'
}

export function getAttendanceStatusTagType(status) {
  if (status === ATTENDANCE_CHECK_IN_STATUS.CHECK_IN_SUCCESS || status === ATTENDANCE_CHECK_IN_STATUS.CHECK_OUT_SUCCESS) {
    return 'success'
  }
  if (
    status === ATTENDANCE_CHECK_IN_STATUS.LOCATION_NOT_CONFIGURED ||
    status === ATTENDANCE_CHECK_IN_STATUS.LOCATION_DISABLED ||
    status === ATTENDANCE_CHECK_IN_STATUS.OUT_OF_RANGE
  ) {
    return 'danger'
  }
  if (status === ATTENDANCE_CHECK_IN_STATUS.ALREADY_FINISHED) {
    return 'warning'
  }
  return 'primary'
}
